config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root'items#index'
  get "/items/show", to: "items#show"
  get  "/buys/index", to: "buys#index"
  get "/sells/index", to: "sells#index"
  get "/cards/index", to: "cards#index"
  
  
  
  
  resources :items  do
    member do
     get :stopExhibit
     get :resumeExhibit
   end
  end
  resources :sells, only: :create
  resources :users, only: [:destroy, :show, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'mypage'
      get 'profile'
      get 'personal'
      get 'sell_item'
    end
    
  end
  resources :signup do
    collection do
      get 'new_member'
      get 'registration'
      get 'sms_confirmation'
      get 'input_address'
      get 'signup_complete'
      end
    end
    resources :cards, only: [:new, :create, :show, :destroy] do
      collection do
        post 'create'
        post 'new'
        post 'show'
        get 'confirmation'
      end
    end
    resources :purchase, only: [:index] do
      member do
        get 'index'
        post 'pay'
        get 'done'
      end
    end
  end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :validates_registration, only: :sms_confirmation
  before_action :validates_sms_confirmation, only: :input_address
  def new_member
  end

  def registration
    @user = User.new
  end
  # registration(会員情報入力)で入力したデータをsessionで仮保存
  def validates_registration
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    # パスワードは6文字以上じゃないと登録できない
    session[:password] = user_params[:password]
    session[:family_name_kanji] = user_params[:family_name_kanji]
    session[:first_name_kanji] = user_params[:first_name_kanji]
    session[:family_name_kana] = user_params[:family_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:birthdata_year] = user_params[:birthdata_year]
    session[:birthdata_month] = user_params[:birthdata_month]
    session[:birthdata_day] = user_params[:birthdata_day]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      family_name_kanji: session[:family_name_kanji],
      first_name_kanji: session[:first_name_kanji],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdata_year: session[:birthdata_year],
      birthdata_month: session[:birthdata_month],
      birthdata_day: session[:birthdata_day],
      phone_number: '09012112362'
    )
    render 'registration' unless @user.valid?
  end
  
  def sms_confirmation
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    # パスワードは6文字以上じゃないと登録できない
    session[:password] = user_params[:password]
    session[:family_name_kanji] = user_params[:family_name_kanji]
    session[:first_name_kanji] = user_params[:first_name_kanji]
    session[:family_name_kana] = user_params[:family_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:birthdata_year] = user_params[:birthdata_year]
    session[:birthdata_month] = user_params[:birthdata_month]
    session[:birthdata_day] = user_params[:birthdata_day]
    @user = User.new
  end

  def validates_sms_confirmation
    session[:phone_number] = user_params[:phone_number]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      family_name_kanji: session[:family_name_kanji],
      first_name_kanji: session[:first_name_kanji],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdata_year: session[:birthdata_year],
      birthdata_month: session[:birthdata_month],
      birthdata_day: session[:birthdata_day],
      phone_number: session[:phone_number]
    )
    render 'sms_confirmation' unless @user.valid?
  end

  # sms_confirmation（電話番号の確認）で入力したデータをsessionで仮保存
  def input_address
    session[:phone_number] = user_params[:phone_number]
    @user = User.new
    @user.build_address
    
  end
# input_address（住所入力）で入力したデータをsessionで仮保存
  def payment
    # のちの作業（payjpを使うとき））で使用予定
    # session[:address_attributes] = user_params[:address_attributes]
    # @user = User.new
    # @user.build_address
  end
# クレジットカードのテーブルを作りsessionで保存
# のちの作業で使用
  
# createアクションでsessionをdbに保存
  def create
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      family_name_kanji: session[:family_name_kanji],
      first_name_kanji: session[:first_name_kanji],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdata_year: session[:birthdata_year],
      birthdata_month: session[:birthdata_month],
      birthdata_day: session[:birthdata_day],
      phone_number: session[:phone_number],
    )
    @user.build_address(user_params[:address_attributes])
    
    if @user.save!
      session[:id] = @user.id
      redirect_to signup_complete_signup_index_path
    else
      render :new_member
    end
  end
  
  def signup_complete
    sign_in User.find(session[:id]) unless user_signed_in?
  end
  private
  def user_params
    params.require(:user).permit(
      :nickname,
      :ntroduce,
      :family_name_kanji,
      :first_name_kanji,
      :family_name_kana,
      :first_name_kana,
      :birthdata_year,
      :birthdata_month,
      :birthdata_day,
      :phone_number,
      :email,
      :password,
      :reset_password_token,
      :reset_password_sent_at,
      :remember_created_at,
      address_attributes: [:id, :family_name, :first_name, :family_name_katakana, :first_name_katakana, :postcode, :prefecture, :city, :block, :building, :telephone_number]
    )
  end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/_registration.html.haml
-# 会員情報入力
.menberInfo__input

  = render "shared/users/headers"
  
  %main.single-main
    %section.l-single-container
      %h2.l-single-head.registration 会員情報入力
      = form_with model: @user, local: true, url: sms_confirmation_signup_index_path, class:"l-single-inner registration-form", method: :get do |f|
        .l-single-content
          .form-group
            = f.label :nickname do
              ニックネーム
            %span.form-require 必須
            = f.text_field :nickname, placeholder: "例）メルカリ太朗", class:"input-default"
          .form-group
            = f.label :email do
              メールアドレス
            %span.form-require 必須
            = f.text_field :email, placeholder: "PC・携帯どちらでも可", class:"input-default"
            .form-group.form-password-revelation
              = f.label :password do
                パスワード
              %span.form-require 必須
              = f.text_field :password, placeholder: "7文字以上の半角英数字", class:"input-default"
              %p.form-info-text
                ※ 英字と数字の両方を含めて設定してください
              .form-password-revelation-toggle
                .checkbox-default
                  %i.icon-check
                  -# 後で実装
                  -# = f.label :reveal_password do
                  -#   パスワードを表示する
                .form-password-revelation-revealed-password-container
                  %span.form-password-revelation-revealed-password
            .form-group
              %h3.text-left.l-chapter-sub-head 本人確認
              %p.l-single-text
                安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .form-group
              %div
                = f.label :family_name_kanji do
                  お名前(全角)
                %span.form-require 必須
              = f.text_field :family_name_kanji, placeholder: "例) 山田", class:"input-default"
              = f.text_field :first_name_kanji, placeholder: "例) 彩", class:"input-default"
            .form-group
              %div
                = f.label :family_name_kana do
                  お名前カナ(全角)
                %span.form-require 必須
              = f.text_field :family_name_kana, placeholder: "例) ヤマダ", class:"input-default"
              = f.text_field :first_name_kana, placeholder: "例) アヤ", class:"input-default"
            .form-group
              = f.label :birthdata_year do
                生年月日
              %span.form-require 必須
              %br/
              .birthday-select-wrap
                .select-wrap
                  %i.icon-arrow-bottom
                  = f.select :birthdata_year, [*1900..2019].reverse, { prompt: "--"}, class:"select-default"
                  %span 年
                .select-wrap.select-wrap__month
                  %i.icon-arrow-bottom
                  = f.select :birthdata_month, [*1..12], { prompt: "--"}, class:"select-default" 
                %span 月
                .select-wrap.select-wrap__day
                  %i.icon-arrow-bottom
                  = f.select :birthdata_day, [*1..31], { prompt: "--"}, class:"select-default"
                %span 日
              -# %input{name: "birthday", type: "hidden", value: ""}/
              .clearfix
            %p.form-info-text
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .l-single-content
            -# %input{name: "after_save_callback", type: "hidden", value: ""}/
            .form-group
              %p.l-single-text.text-center
                「次へ進む」のボタンを押すことにより、
                =link_to "#" do
                  利用規約
                に同意したものとみなします
                = f.submit value: "次へ進む", class:"btn-default btn-red"
              .form-group.text-right
              %p
                =link_to "#" do
                  本人情報の登録について
                  %i.icon-arrow-right
  = render "shared/users/footers"

app/views/signup/index.html.haml
-# 新規会員登録ページ
.menberSignup__wrapper

  = render "shared/users/header"

  %main.single__main
  %section.l__single__container
    %h2.l__single__head.registration 新規会員登録
    .l__single__inner.registration__form
      .l__single__content
        .btn__default.btn__mail{href: "#"}
          %i.icon-mail
          = link_to "メールアドレスで登録する", registration_signup_index_path
        %button#facebook__login.btn__default.btn__sns.btn__sns--facebook
          %i.icon-facebook
          = link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, method: :post
        %button#google__login.btn__default.btn__sns.btn__sns__google
          = link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, method: :post

  = render "shared/users/footer"

app/views/signup/input_address.html.haml
.input__address__wrapper
  
  = render "shared/users/headers"

  %main.single-main
    %section.l-single-container
      %h2.l-single-head.registration 住所入力
      = form_with model: @user, local: true, url: signup_index_path, class:"l-single-inner registration-form", method: :post do |f|
        = f.fields_for :address do |address_form|
          .l-single-content
            .form-group
              = address_form.label :family_name do
                お名前
              %span.form-require 必須
              = address_form.text_field :family_name, placeholder: "例) 山田", class:"input-default"
              = address_form.text_field :first_name, placeholder: "例) 彩", class:"input-default"
            .form-group
              = f.label :family_name_kana do
                お名前カナ
              %span.form-require 必須
              = address_form.text_field :family_name_katakana, placeholder: "例) ヤマダ", class:"input-default"
              = address_form.text_field :first_name_katakana, placeholder: "例) アヤ", class:"input-default"
            .form-group.form-password-revelation
              = address_form.label :postcode do
                郵便番号
              %span.form-require 必須
              = address_form.text_field :postcode, placeholder: "例）123-4567", class:"input-default"
              .form-group
                = address_form.label :prefecture do
                  都道府県
                %span.form-require 必須
                .prefectures-select.tab
                  = address_form.select :prefecture, class:"prefecture-select-default" do
                    %option{value: ""} 選択してください
                    %option{value: "北海道"} 北海道
                    %option{value: "青森県"} 青森県
                    %option{value: "岩手県"} 岩手県
                    %option{value: "宮城県"} 宮城県
                    %option{value: "秋田県"} 秋田県
                    %option{value: "山形県"} 山形県
                    %option{value: "福島県"} 福島県
                    %option{value: "茨城県"} 茨城県
                    %option{value: "栃木県"} 栃木県
                    %option{value: "群馬県"} 群馬県
                    %option{value: "埼玉県"} 埼玉県
                    %option{value: "千葉県"} 千葉県
                    %option{value: "東京都"} 東京都
                    %option{value: "神奈川県"} 神奈川県
                    %option{value: "新潟県"} 新潟県
                    %option{value: "富山県"} 富山県
                    %option{value: "石川県"} 石川県
                    %option{value: "福井県"} 福井県
                    %option{value: "山梨県"} 山梨県
                    %option{value: "長野県"} 長野県
                    %option{value: "岐阜県"} 岐阜県
                    %option{value: "静岡県"} 静岡県
                    %option{value: "愛知県"} 愛知県
                    %option{value: "三重県"} 三重県
                    %option{value: "滋賀県"} 滋賀県
                    %option{value: "京都府"} 京都府
                    %option{value: "大阪府"} 大阪府
                    %option{value: "兵庫県"} 兵庫県
                    %option{value: "奈良県"} 奈良県
                    %option{value: "和歌山県"} 和歌山県
                    %option{value: "鳥取県"} 鳥取県
                    %option{value: "島根県"} 島根県
                    %option{value: "岡山県"} 岡山県
                    %option{value: "広島県"} 広島県
                    %option{value: "山口県"} 山口県
                    %option{value: "徳島県"} 徳島県
                    %option{value: "香川県"} 香川県
                    %option{value: "愛媛県"} 愛媛県
                    %option{value: "高知県"} 高知県
                    %option{selected: "selected", value: "福岡県"} 福岡県
                    %option{value: "佐賀県"} 佐賀県
                    %option{value: "長崎県"} 長崎県
                    %option{value: "熊本県"} 熊本県
                    %option{value: "大分県"} 大分県
                    %option{value: "宮崎県"} 宮崎県
                    %option{value: "鹿児島県"} 鹿児島県
                    %option{value: "沖縄県"} 沖縄県
              .form-group
                = address_form.label :city do
                  市区町村
                %span.form-require 必須
                = address_form.text_field :city, placeholder: "例）横浜市緑区", class:"input-default"
              .form-group
                = address_form.label :block do
                  番地
                %span.form-require 必須
                = address_form.text_field :block, placeholder: "例）青山1-1-1", class:"input-default"
              .form-group
                = address_form.label :building do
                  建物名
                %span.form-lay 任意
                = address_form.text_field :building, placeholder: "例）○○ビル", class:"input-default"
              .form-group
                = address_form.label :telephone_number do
                  電話番号
                %span.form-lay 任意
                = address_form.text_field :telephone_number, placeholder: "例）123456789", class:"input-default"
              = f.submit value: "次へ進む", class:"btn-default btn-red"
      
    = render "shared/users/footers"     
      
        

app/views/signup/new_member.html.haml
-# 新規会員登録ページ
.menberSignup__wrapper

  = render "shared/users/header"

  %main.single__main
  %section.l__single__container
    %h2.l__single__head.registration 新規会員登録
    .l__single__inner.registration__form
      .l__single__content
        .btn__default.btn__mail
          %i.icon-mail
          = fa_icon "envelope", class: "fontawesome_icon"
          = link_to "メールアドレスで登録する", registration_signup_index_path, class:"signup__mail"
        %button#facebook__login.btn__default.btn__sns.btn__sns--facebook
          %i.icon-facebook
          = fa_icon "facebook-square", class: "fontawesome_icon"
          = link_to "Facebookで登録する", user_facebook_omniauth_authorize_path, class:"signup__facebook", method: :post
        %button#google__login.btn__default.btn__sns.btn__sns__google
          %i.icon-google
          = image_tag 'google_icon.png',class: "google"
          = link_to "Googleで登録する", user_google_oauth2_omniauth_authorize_path, method: :post

  = render "shared/users/footer"

app/views/signup/new_menber.html.haml
-# 新規会員登録ページ
.menberSignup__wrapper

  = render "shared/users/header"

  %main.single__main
  %section.l__single__container
    %h2.l__single__head.registration 新規会員登録
    .l__single__inner.registration__form
      .l__single__content
        .btn__default.btn__mail{href: "#"}
          %i.icon-mail
          =link_to  "メールアドレスで登録する", "#"
        %button#facebook__login.btn__default.btn__sns.btn__sns--facebook
          %i.icon-facebook
          Facebookで登録する
        %button#google__login.btn__default.btn__sns.btn__sns__google
          Googleで登録する

  = render "shared/users/footer"

app/views/signup/registration.html.haml
-# 会員情報入力
.menberInfo__input

  = render "shared/users/headers"
  
  %main.single-main
    %section.l-single-container
      %h2.l-single-head.registration 会員情報入力
      = form_with model: @user, local: true, url: sms_confirmation_signup_index_path, class:"l-single-inner registration-form", method: :get do |f|
        .l-single-content
          .form-group
            = f.label :nickname do
              ニックネーム
            %span.form-require 必須
            = f.text_field :nickname, placeholder: "例）メルカリ太朗", class:"input-default"
          .form-group
            = f.label :email do
              メールアドレス
            %span.form-require 必須
            = f.text_field :email, placeholder: "PC・携帯どちらでも可", class:"input-default"
            .form-group.form-password-revelation
              = f.label :password do
                パスワード
              %span.form-require 必須
              = f.text_field :password, placeholder: "7文字以上の半角英数字", class:"input-default"
              %p.form-info-text
                ※ 英字と数字の両方を含めて設定してください
              .form-password-revelation-toggle
                .checkbox-default
                  %i.icon-check
                  -# 後で実装
                  -# = f.label :reveal_password do
                  -#   パスワードを表示する
                .form-password-revelation-revealed-password-container
                  %span.form-password-revelation-revealed-password
            .form-group
              %h3.text-left.l-chapter-sub-head 本人確認
              %p.l-single-text
                安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .form-group
              %div
                = f.label :family_name_kanji do
                  お名前(全角)
                %span.form-require 必須
              = f.text_field :family_name_kanji, placeholder: "例) 山田", class:"input-default"
              = f.text_field :first_name_kanji, placeholder: "例) 彩", class:"input-default"
            .form-group
              %div
                = f.label :family_name_kana do
                  お名前カナ(全角)
                %span.form-require 必須
              = f.text_field :family_name_kana, placeholder: "例) ヤマダ", class:"input-default"
              = f.text_field :first_name_kana, placeholder: "例) アヤ", class:"input-default"
            .form-group
              = f.label :birthdata_year do
                生年月日
              %span.form-require 必須
              %br/
              .birthday-select-wrap
                .select-wrap
                  %i.icon-arrow-bottom
                  = f.select :birthdata_year, [*1900..2019].reverse, { prompt: "--"}, class:"select-default"
                %span_span 年
                .select-wrap.select-wrap__month
                  %i.icon-arrow-bottom
                  = f.select :birthdata_month, [*1..12], { prompt: "--"}, class:"select-default" 
                %span_span 月
                .select-wrap.select-wrap__day
                  %i.icon-arrow-bottom
                  = f.select :birthdata_day, [*1..31], { prompt: "--"}, class:"select-default"
                %span_span 日
              -# %input{name: "birthday", type: "hidden", value: ""}/
              .clearfix
            %p.form-info-text
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .l-single-content
            -# %input{name: "after_save_callback", type: "hidden", value: ""}/
            .form-group
              %p.l-single-text.text-center
                「次へ進む」のボタンを押すことにより、
                =link_to "#" do
                  利用規約
                に同意したものとみなします
                = f.submit value: "次へ進む", class:"btn-default btn-red"
              .form-group.text-right
              %p
                =link_to "#" do
                  本人情報の登録について
                  %i.icon-arrow-right
  = render "shared/users/footers"

app/views/signup/signup_complete.html.haml
.signUp__complete
  
  = render "shared/users/headers"
  
  %main.single-main
  %section.l-single-container
    %h2.l-chapter-head.registration 会員登録完了
    .complete-text
      %p ありがとうございます。
      %p 会員登録完了しました。
      %button.btn-default.btn-red{type: "submit"} SMSを送信する
      .advertisement__img
        = image_tag 'advertisement.png'

  = render "shared/users/footers"

app/views/signup/sms_confirmation.html.haml
.sms__confirmation__warraper
  
  = render "shared/users/headers"

  %main.single-main
  %section.l-single-container
    %h2.l-chapter-head.registration 電話番号の確認
    = form_with model: @user, local: true, url:input_address_signup_index_path, class:"l-single-inner registration-form", method: :get do |f|
      .l-single-content
        .form-group
          = f.label :phone_number do
            携帯電話の番号
        = f.text_field :phone_number, placeholder: "携帯電話の番号を入力", class:"input-default"
        %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
        = f.submit value: "SMSを送信する", class:"btn-default btn-red"
        %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
        .form-group.text-right
          = link_to "#" do 
            電話番号の確認が必要な理由
            %i.icon-arrow-right
      -# %input{name: "__csrf_value", type: "hidden", value: "#"}/
      -# %input{name: "id", type: "hidden", value: "#"}/   
  = render "shared/users/footers"