config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root'items#index'
  get "/items/show", to: "items#show"
  get  "/buys/index", to: "buys#index"
  get "/sells/index", to: "sells#index"
  get "/cards/index", to: "cards#index"
  
  
  
  
  resources :items  do
    member do
     get :stopExhibit
     get :resumeExhibit
   end
  end
  resources :sells, only: :create
  resources :users, only: [:destroy, :show, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'mypage'
      get 'profile'
      get 'personal'
      get 'sell_item'
    end
    
  end
  resources :signup do
    collection do
      get 'new_member'
      get 'registration'
      get 'sms_confirmation'
      get 'input_address'
      get 'signup_complete'
      end
    end
    resources :cards, only: [:new, :create, :show, :destroy] do
      collection do
        post 'create'
        post 'new'
        post 'show'
        get 'confirmation'
      end
    end
    resources :purchase, only: [:index] do
      member do
        get 'index'
        post 'pay'
        get 'done'
      end
    end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_one :address
  has_many :sns_credentials, dependent: :destroy
  has_one :card
  accepts_nested_attributes_for :address
  has_many :items

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  VALID_PHONE_REGEX = /\A\d{10,11}\z/
  VALID_KATAKANA_REGEX = /\A[ァ-ヶー－]+\z/
  # registrationのバリデーション
  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 7 }, format: { with: VALID_PASSWORD_REGEX }
  validates :family_name_kanji, presence: true
  validates :first_name_kanji, presence: true
  validates :family_name_kana, presence: true, format: { with: VALID_KATAKANA_REGEX }
  validates :first_name_kana, presence: true, format: { with: VALID_KATAKANA_REGEX }
  validates :birthdata_year, presence: true, numericality: true 
  validates :birthdata_month, presence: true, numericality: true
  validates :birthdata_day, presence: true, numericality: true
  # sms-confirmationのバリデーション
  validates :phone_number, presence: true, format: { with: VALID_PHONE_REGEX }
         

      def self.from_omniauth(auth)
        user = User.find_by(email: auth.info.email)
        sns_credential_record = SnsCredential.where(provider: auth.provider, uid: auth.uid)
        if user.present?
          unless sns_credential_record.present?
            SnsCredential.create(
              provider: auth.provider,
              uid: auth.uid
            )
          end
        elsif
          user = User.new(
            email: auth.info.email,
            password: Devise.friendly_token[0, 20],
            nickname: auth.info.name,
          )
          SnsCredential.new(
            provider: auth.provider,
            uid: auth.uid,
          )
        end 
      user
      end
    end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?  
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else 
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to registration_signup_index_path
    end
  end
    

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: 'google') if is_navigational_format?
    else
      session["omniauth.google_data"] = request.env["omniauth.auth"][:info]
      redirect_to registration_signup_index_path
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :check_captcha, only: [:create]

  def index
  end

  def create
    build_resource(sign_up_params)
    resource.save
    profile = Profile.new({ nickname: resource.nickname, user_id: resource.id })
    profile.save(validate: false)
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  private

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :password_confirmation])
  end

  def check_captcha
    self.resource = resource_class.new sign_up_params
    resource.validate
    unless verify_recaptcha(model: resource)
      render :new
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :check_captcha, only: [:create]

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    user = User.find(resource.id)
    if user.profile.blank?
      profile = Profile.new({ nickname: user.nickname, user_id: user.id })
      profile.save(validate: false)
    end
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  private

  def check_captcha
    self.resource = resource_class.new sign_in_params
    resource.validate
    remove_unique_validation(resource)
    unless verify_recaptcha(model: resource)
      render :new
    end
  end

  def remove_unique_validation(resource)
    if resource.errors.details[:email].present? && resource.errors.details[:email][0][:error].to_s == "taken"
      resource.errors[:email].pop
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user , only: [:personal,:profile,:mypage]

    def personal
    end
   

    def profile
    end

    def mypage
    end

    def logout
    end

    def sell_item
        @items = Item.where(user_id: current_user.id)
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.haml
.contents__bottom__image
  .contents__bottom__image__detail
    .contents__bottom__image__left
      %p.contents__bottom__left__text
        スマホで簡単フリマアプリ
        %p.contents__bottom__left__texts
          今すぐ無料ダウンロード！
      .contents__bottom__icon
        = image_tag "logo_red.svg", size: "68x68"
        .contents__bottom__app
          = link_to "#", target: "_blank" do
            = image_tag "app.jpg", size: "144x40"
        .contents__bottom__google
          = link_to "#", target: "_blank" do
            = image_tag "google.png", size: "144x40"
    .contents__bottom__image__right
      = image_tag "スマホ.jpg", size: "300x260" 
.footer
  %nav
    .footer__left
      %h2.heading
        メルカリについて
      %ul
        %li.footer__list
          = link_to "#" do 
            会社概要（運営会社）
        %li.footer__list
          = link_to "#" do
            採用情報
        %li.footer__list
          = link_to "#" do
            プレスリリース
        %li.footer__list
          = link_to "#" do
            公式ブログ
        %li.footer__list
          = link_to "#" do
            メルカリロゴ利用ガイドライン
    .footer--help
      %h2.heading
        ヘルプ＆ガイド
      %ul
        %li.footer__list
          = link_to "#" do
            メルカリガイド
        %li.footer__list
          = link_to "#" do
            らくらくメルカリ便
        %li.footer__list
          = link_to "#" do
            ゆうゆうメルカリ便
        %li.footer__list
          = link_to "#" do
            大型メルカリ便
        %li.footer__list
          = link_to "#" do
            車体取引ガイド
        %li.footer__list
          = link_to "#" do
            メルカリあんしん・あんぜん宣言！
        %li.footer__list
          = link_to "#" do
            偽ブランド品撲滅への取り組み
        %li.footer__list
          = link_to "#" do
            メルカリボックス
    .footer__center
      %h2.heading
        プライバシーと利用規約
      %ul
        %li.footer__list
          = link_to "#" do
            プライバシーポリシー
        %li.footer__list
          = link_to "#" do
            メルカリ利用規約
        %li.footer__list
          = link_to "#" do
            安心スマホサポート制度に関する利用規約
        %li.footer__list
          = link_to "#" do
            コンプライアンスポリシー
    .footer__center__right
      %ul
        %li.footer__list
          = link_to "#" do
            個人データの安全管理に係る基本方針
        %li.footer__list
          = link_to "#" do
            特定商取引に関する表記
        %li.footer__list
          = link_to "#" do
            資金決済法に基づく表示
        %li.footer__list
          = link_to "#" do
            法令順序と犯罪抑止の為にために
    .footer__right
      %h2.heading
        国
      %ul
        %li.footer__list
          = link_to "#" do
            日本
        %li.footer__list
          = link_to "#" do
            United States
  .footer__end
    %a.footer__bottom
      = image_tag "fmarket_logo_white.svg", size: "134x36", href: "http://google.co.jp"
      %span
        © Mercari, Inc.

app/views/users/_header.html.haml
#__next
  .header__t
    .header
      .header__box
        .header__input__box
          %a.header--image
            = link_to root_path, class: "header--image" do
              = image_tag "fmarket_logo_red.svg", size: "134x36"
          .foom
            %input.search__box{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: ""}/
            %button.header--btn
              -# %i.fa.fa-search
        .header__bottom
          .header__bottom__left
            = link_to "カテゴリーから探す", '#',class:"category"
            = link_to "ブランドから探す", '#',class:"brand"
          .header__bottom__right
            %ul.header__navi
            %li.header__navi__link
            =fa_icon "heart", class:"hert_icon"
            = link_to "いいね！一覧", '#',class:"link"
            -# %i.far.fa-heart
            =fa_icon "bell", class:"bell_icon"
            = link_to "お知らせ", "#" ,class:"menu"
            -# %i.icon-bell
            =fa_icon "check", class:"check_icon"
            = link_to "やることリスト", "#" ,class:"link"
            %i.icon-check
            =fa_icon "user", class:"user_icon"
            = link_to "マイページ",   mypage_user_path(current_user.id) ,class:"link"
  %nav.bread__list
    %ul
      = render "shared/breadcrumbs"     

app/views/users/_kamera.html.haml
%a.sell__btn{href: "/sells/index"}
    .sell__btn__name 出品
    = fa_icon "camera", class: "camera"

app/views/users/_kameras.html.haml
%a.sell__btn{href: "/users/sign_in"}
    .sell__btn__name 出品
    = fa_icon "camera", class: "camera"

app/views/users/_left_side_bar.html.haml
.left__main
  %ul.left__main
    %li.left__main__list
      = link_to "マイページ", mypage_user_path(current_user.id) ,class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "お知らせ", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "やることリスト", '#' ,class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "いいね！一覧", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "出品する", sells_index_path ,class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "出品した商品 - 出品中", sell_item_user_path(current_user.id),class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "出品した商品 - 取引中", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "出品した商品 - 売却済み", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "購入した商品 - 取引中", '#' ,class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to " 購入した商品 - 過去の取引", '#' ,class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to " ニュース一覧", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to " 評価一覧", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "ガイド", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "お問い合わせ", '#',class:"item"
      %i.icon-arrow-right
    %h3.main__list__head メルペイ
    %ul.mypage__list
    %li.left__main__list
      = link_to "売上・振込申請", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "ポイント", '#',class:"item"
      %i.icon-arrow-right
    %h3.main__list__head 設定
    %ul.mypage__list
    %li.left__main__list
      = link_to "プロフィール", profile_user_path(current_user.id),class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to " 発送元・お届け先住所変更", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "支払い方法", confirmation_cards_path,class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "メール/パスワード", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to " 本人情報", personal_user_path(current_user.id) ,class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to "電話番号の確認", '#',class:"item"
      %i.icon-arrow-right
    %li.left__main__list
      = link_to " ログアウト",  logout_users_path ,class:"item"
      %i.icon-arrow-right

app/views/users/create.html.haml
- breadcrumb :user_create
=render "users/header"
.identification__all.clearfix
  .identification__all__content
    %section.identification__all__right
      %h2.identification__all__mypage 本人情報の登録
    %form.identification__all__inner{action: "#", method: "POST", novalidate: ""}
      %div
        %p.identification__all__text
        お客さまの本人情報をご登録ください。
        %br>/
        登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.identification__all__up
          = link_to "#", target: "_blank", class: "upload" do
            本人確認書類のアップロードについて
            %i.icon-arrow-right
      .identification__all__form
        %label お名前
        %p ナナシ
      .identification__all__form
        %label お名前カナ
        %p ナナシ
      .identification__all__form
        %label{for: "birthday"} 生年月日
        %p 2019/12/10
      .identification__all__form
        %label{for: "zip_code"} 郵便番号
        %span.identification__all__arbitrary 任意
        %input.input__default{name: "zip_code", placeholder: "例）1234567", type: "text", value: ""}/
      .identification__all__form
        %label{for: "prefecture"} 都道府県
        %span.identification__all__arbitrary 任意
        .identification__all__prefecture
          %i.icon-arrow-bottom
          %select.identification__all__default{name: "prefecture"}
            %option --
            %option 北海道
            %option 青森県
            %option 岩手県
            %option 宮城県
            %option 秋田県
            %option 山形県
            %option 福島県
            %option 東京都
            %option 神奈川県
            %option 埼玉県
            %option 千葉県
            %option 茨城県
            %option 栃木県
            %option 群馬県
            %option 山梨県
            %option 新潟県
            %option 長野県
            %option 富山県
            %option 石川県
            %option 福井県
            %option 愛知県
            %option 岐阜県
            %option 静岡県
            %option 三重県
            %option 大阪府
            %option 兵庫県
            %option 京都府
            %option 滋賀県
            %option 奈良県
            %option 和歌山県
            %option 鳥取県
            %option 島根県
            %option 岡山県
            %option 広島県
            %option 山口県
            %option 徳島県
            %option 香川県
            %option 愛媛県
            %option 高知県
            %option 福岡県
            %option 佐賀県
            %option 長崎県
            %option 熊本県
            %option 大分県
            %option 宮崎県
            %option 鹿児島県
            %option 沖縄県
      .identification__all__form
        %label{for: "city"} 市区町村
        %span.identification__all__arbitrary 任意
        %input.input__default{name: "city", placeholder: "例) 横浜市緑区", type: "text", value: ""}/
      .identification__all__form
        %label{for: "address1_label"} 番地
        %span.identification__all__arbitrary 任意
        %input.input__default{name: "address1", placeholder: "例) 青山1−1−1", type: "text", value: ""}/
      .identification__all__form
        %label{for: "address2_label"} 建物名
        %span.identification__all__arbitrary 任意
        %input.input__default{name:"address2", placeholder: "例) 柳ビル103", type: "text", value: ""}/
      %button.identification__all__btn{type: "submit"} 登録する
      .identification__all__text
        = link_to "#", target: "_blank", class: "upload" do
          本人情報の登録について
          %i.icon-arrow-right
      %input{name: "__csrf_value", type: "hidden", value: ""}/
    =render "users/kamera"
  =render "users/left_side_bar"
=render "users/footer"

app/views/users/destroy.html.haml
- breadcrumb :logout
=render "users/header"
.main__all.clearfix
  .content__all
    .right__content__container
      .logout__form
        .main__logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "main__logout__btn"
    =render "users/kamera"
  =render "users/left_side_bar"
=render "users/footer"  

app/views/users/mypage.html.haml
- breadcrumb :user_mypage
=render "users/header"

.mypage__view.clearfix
  .mypage__view__all
    %section.mypage__view__user-icon
      = link_to "", '#', class:""
      .figure
        = image_tag "mypage-icon.jpg", size: "60x60", class:"user"
      .mypage__view__user__name 
        = @user.nickname
      .mypage__view__number
        .mypage__view__name
          評価
          %span.bold 0
        .mypage__view__name
          出品数
          %span.bold 0
    %section.mypage__view__tab
      %ul.mypage__view__tabs
        %li.active
          .mypage__view__informatiom
            = link_to "お知らせ", "#" ,class:"information"
            %span.mypage__view__nav__number
              38
        %li.active__two
          .mypage__view__informatiom
            = link_to "やることリスト", "#",class:"information"
            %span.mypage__view__nav__number
              1
      .tab__content
        %ul.tab__content__list
          %li
            .tab__content__link
              = link_to "", '#',class:"#"
              .lazyloaded
                = image_tag "icon.jpg", size: "60x60"
              .mypage__view__body
                .mypage__view__text【必ずP3,000もらえる！？】今のうちに買うシカない！
                %time
                  %i.icon__time
                  %span 5 時間前
              %i.icon-arrow-right
          %li
            .tab__content__link
              = link_to "", '#',class:"#"
              .lazyloaded
                = image_tag "icon.jpg", size: "60x60"
              .mypage__view__body
                .mypage__view__text 購入ごとに最大3％還元！お支払い方法は《メルペイスマート払い》が一番お得
                %time
                  %i.icon__time
                  %span 1 日前
              %i.icon-arrow-right
          %li
            .tab__content__link
              = link_to "", '#',class:"#"
              .lazyloaded
                = image_tag "icon.jpg", size: "60x60"
              .mypage__view__body
                .mypage__view__text 購入ごとに最大3％還元！お支払い方法は《メルペイスマート払い》が一番お得
                %time
                  %i.icon__time
                  %span 1 日前
              %i.icon-arrow-right
          %li
            .tab__content__link
              = link_to "", '#',class:"#"
              .lazyloaded
                = image_tag "icon.jpg", size: "60x60"
              .mypage__view__body
                .mypage__view__text 購入ごとに最大3％還元！お支払い方法は《メルペイスマート払い》が一番お得
                %time
                  %i.icon__time
                  %span 1 日前
              %i.icon-arrow-right
          %li
            .tab__content__link
              = link_to "", '#',class:"#"
              .lazyloaded
                = image_tag "icon.jpg", size: "60x60"
              .mypage__view__body
                .mypage__view__text 購入ごとに最大3％還元！お支払い方法は《メルペイスマート払い》が一番お得
                %time
                  %i.icon__time
                  %span 1 日前
              %i.icon-arrow-right
          %li.mypage-go-list
          = link_to "", '#',class:"#"
        %ul.tab__content__list
          %li
            .tab__content__link
              = link_to "", '#',class:"#"
              .lazyloaded
                = image_tag "icon.jpg", size: "60x60"
              .mypage__view__body
                .mypage__view__text ご登録のメールアドレスに認証メールを送りました。メールに記載のURLをクリックして、メールアドレスを認証してください。
                %time
                  %i.icon__time
                  %span 61 日前
              %i.icon-arrow-right
          %li.tab__content__link
            = link_to "一覧を見る", '#',class:"list"
    %aside.modal{"data-close" => "modal", "data-modal" => "banner"}   
    %section.mypage__tab__footer
      %h2.mypage__tab__head 購入した商品
      %ul.mypage__view__tabs
        %li.active
          .mypage__view__informatiom
            = link_to "取引中", '#',class:"trading"    
        %li.active__two
          .mypage__view__informatiom
            = link_to "過去の取引", '#',class:"transactions"
      .tab__content
        %ul.tab__content__active
          %li.tab__content__item 取引中の商品がありません
        %ul.tab__content__active
    =render "users/kamera"
  =render "users/left_side_bar"
=render "users/footer" 

app/views/users/new_menber.html.haml
-# 新規会員登録ページ
.menberSignup__wrapper

  = render "shared/users/header"

  %main.single__main
  %section.l__single__container
    %h2.l__single__head.registration 新規会員登録
    .l__single__inner.registration__form
      .l__single__content
        .btn__default.btn__mail{href: "#"}
          %i.icon-mail

          =link_to  "メールアドレスで登録する", "#"
        %button#facebook__login.btn__default.btn__sns.btn__sns--facebook

          = link_to "メールアドレスで登録する", registration_signup_index_path
        %button#facebook__login.btn__default.btn__sns.btn__sns--facebook 

          %i.icon-facebook
          = link_to " Facebookで登録する", user_facebook_omniauth_authorize_path, method: :post
        %button#google__login.btn__default.btn__sns.btn__sns__google
          %i.icon-google
          = link_to "Googleで登録する", user_google_oauth2_omniauth_authorize_path, method: :post
          

  = render "shared/users/footer"

app/views/users/profile.html.haml
- breadcrumb :user_profile
=render "users/header"
.content__all__view.clearfix
  .main__profile
    %section.profile__all
      %h2.main__content__profile__head プロフィール
      %form.main__content__form{action: "#"}
        %input.main__content__input{name: "__csrf_value", type: "hidden", value: "#"}/
        .profile__main
          %figure.profile__main__figure
            = image_tag "プロフィール.jpg", size: "60x60"
          %input.profile__main__input{name: "nickname", placeholder: "例)AYA☆セール中", type: "text", value: @user.nickname}/
        .profile__main__content
          %textarea.extarea__main{name: "introduction", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          %input.extarea__main__input{name: "after_save_callback", type: "hidden", value: "#"}/
          %button.extarea__main__btn{type: "submit"} 変更する
    =render "users/kamera"
  =render "users/left_side_bar"
=render "users/footer" 
  

app/views/users/sell_item.html.haml
- breadcrumb :user_sell_item
=render "users/header"

.user__sell__l-container
  .user__sell__myitem
    %section.user__sell__myitem--title
      %h2.user__sell__myitem--head 出品した商品
      %ul.user__sell__myitem--status
        %li.user__sell__myitem--status--title.active
          %h3
            =link_to "出品中" , "#", data: {toggle: "tab"}
        %li.user__sell__myitem--status--title
          %h3
            =link_to "取引中" , "#", data: {toggle: "tab"}
        %li.user__sell__myitem--status--title
          %h3
            =link_to "売却済み" , "#" ,data: {toggle: "tab"}
      .user__sell__myitem--tab
      - @items.each do |item|
        %ul#transaction__now.active
          %li
            =link_to "", "#", class: "sell__item__link" 
            = image_tag  item.images[0], class: "sell__photo",size: "48x48"
            .user__sell__myitem--body
              .user__sell__myitem--body--text 
              = item.products
              .user__sell__myitem--body--status
                .sell__status 
                  =link_to item.status , item_path(item), class: "sell__status "
                
    =render "users/kamera"
  =render "users/left_side_bar"
=render "users/footer" 

app/views/users/update.html.haml
- breadcrumb :user_update
=render "users/header"
.content__all__view.clearfix
  .main__profile
    %section.profile__all
      %h2.main__content__profile__head プロフィール
      %form.main__content__form{action: "#"}
        %input.main__content__input{name: "__csrf_value", type: "hidden", value: "#"}/
        .profile__main
          %figure.profile__main__figure
            = image_tag "プロフィール.jpg", size: "60x60"
          %input.profile__main__input{name: "nickname", placeholder: "例)AYA☆セール中", type: "text", value: "永瀬翔吾"}/
        .profile__main__content
          %textarea.extarea__main{name: "introduction", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          %input.extarea__main__input{name: "after_save_callback", type: "hidden", value: "#"}/
          %button.extarea__main__btn{type: "submit"} 変更する
    =render "users/kamera"
  =render "users/left_side_bar"
=render "users/footer" 
  