config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root'items#index'
  get "/items/show", to: "items#show"
  get  "/buys/index", to: "buys#index"
  get "/sells/index", to: "sells#index"
  get "/cards/index", to: "cards#index"
  
  
  
  
  resources :items  do
    member do
     get :stopExhibit
     get :resumeExhibit
   end
  end
  resources :sells, only: :create
  resources :users, only: [:destroy, :show, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'mypage'
      get 'profile'
      get 'personal'
      get 'sell_item'
    end
    
  end
  resources :signup do
    collection do
      get 'new_member'
      get 'registration'
      get 'sms_confirmation'
      get 'input_address'
      get 'signup_complete'
      end
    end
    resources :cards, only: [:new, :create, :show, :destroy] do
      collection do
        post 'create'
        post 'new'
        post 'show'
        get 'confirmation'
      end
    end
    resources :purchase, only: [:index] do
      member do
        get 'index'
        post 'pay'
        get 'done'
      end
    end
  end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :images
  belongs_to :user, optional: true
  
  # accepts_nested_attributes_for :brand
  enum category:  {'選択してください':0,'レディース':1, 'ベビー・キッズ':2,'インテリア・住まい・小物':3,'本音楽・ゲーム':4,'おもちゃ・ホビー・グッズ':5,'コスメ・香水・美容':6,'家電・スマホ・カメラ':7,'スポーツ・レジャー':8,'ハンドメイド':9,'チケット':10,'自転車・オートバイ':11,'その他':12},_suffix: true
  enum shipping_date:  {'選択してください':0,'1~2日で配送':1, '2~3日で配送':2,'4~7日で配送':3},_suffix: true
  enum shipping_method:  {'選択してください':0,'未定':1, 'らくらくメルカリ便':2,'ゆうメール':3, 'レターパック': 4, '普通郵便（定形、定形外）':5, 'クロネコヤマト': 6, 'ゆうパック': 7, 'クリックポスト':8, 'ゆうパケット': 9},_suffix: true
  enum postage:  {'選択してください':0,'送料込み（出品者負担）':1, '着払い（購入者負担）':2},_suffix: true
  enum condition:  {'選択してください':0,'新品/未使用':1, '未使用に近い':2, '目立った傷や汚れなし': 3, 'やや傷や汚れあり':4, 'キズや汚れあり':5, '全体的に状態が悪い':6},_suffix: true
  enum size: {'選択してください':0,'XXS以下':1, 'XS(SS)':2,'S':3, 'M':4, 'L':5, 'XL(LL)':6, '2XL(3L)':7, '3XL(4L)':8, '4XL(5L)以上':9, 'FREESIZE':10, '20cm以下':11, '20.5cm':12, '21cm':13, '21cm':14, '21.5cm':15, '22cm':16, '22.5cm':17, '23cm':18,      '24cm':19, '24.5cm': 20, '25cm':21, '25.5cm': 22, '26cm': 23, '26.5cm': 24, '27cm': 25, '27.5cm以上': 26},_suffix: true
  enum shipping_origin: {'選択してください':0,'北海道':1,'青森県':2 ,'岩手県':3 ,'宮城県':4 ,'秋田県':5 ,'山形県':6 ,'福島県':7 ,'茨城県':8 ,'栃 木県':9 ,'群馬県':10 ,'埼玉県':11 ,'千葉県':12 ,'東京都':13 ,'神奈川県':14 ,'新潟県':15 ,'富山県':16 ,'石川県':17 ,'福井県':18 ,'山梨県':19 ,'長野県':20 ,'岐阜県':21 ,'静岡県':22 ,'愛知県':23 ,'三重県':24 , '滋賀県':25 ,'京都府':26 ,'大阪府':27 ,'兵庫県':28 ,'奈良県':29 ,'和歌山県':30 ,'鳥取県':31 ,'島根県':32 ,'岡山県':33 ,'広島県':34 ,'山口県':35 ,'徳島県':36 ,'香川県':37 ,'愛媛県':38 ,'高知県':39 ,'福岡県':40 ,'佐賀県':41 ,'長崎県':42 ,'熊本県':43 ,'大分県':44 ,'宮崎県':45 ,'鹿児島県':46 ,'沖縄県':47},_suffix: true
  enum status: { '出品中': 0, '出品停止中': 1, '取引中': 2}
  
  

  #validation
  validates :products, presence: true, length: { maximum: 40 }
  validates :description_of_item, presence: true, length: { maximum: 1000 }
  validates :price,  presence: true
  validates :price,  inclusion: 300..9999999, allow_blank: true
  validates :category, presence: true
  validates :condition, presence: true
  validates :size, presence: true
  validates :shipping_date, presence: true
  validates :shipping_method, presence: true
  validates :postage, presence: true
  validates :shipping_origin, presence: true
  validates :user_id, presence: true
  validate :images_presence

  def images_presence
    if images.attached?
      images.each do |image|
        if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
          image.purge
          errors.add(:images, 'には画像ファイルを添付してください')
        end
      end
    else
      errors.add(:images, 'がありません')
    end
  end

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item , only: [:show, :edit, :update, :destroy, :stopExhibit,:resumeExhibit ]

  def index
    @items = Item.limit(10).order("created_at DESC")
  end
  
  def show
    @items = Item.where(user_id: @item.user.id).includes(:user).limit(6).order("created_at DESC")
  end


  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end


  def destroy
    if @item.user_id == current_user.id
      @item.destroy
      redirect_to root_path
    end
  end

  def stopExhibit
   if @item.update(status: "出品停止中")
    redirect_to item_path, notice: "出品を一旦停止しました"
   else
    redirect_to item_path, notice: "エラー！変更に失敗しました。再度変更お願いします。"
   end
  end

  def resumeExhibit
   if @item.update(status: "出品中")
    redirect_to item_path, notice: "出品を再開しました"
   else
    redirect_to item_path, notice: "エラー！変更に失敗しました。再度変更お願いします。"
   end
  end


  
  
  private
  def item_params
    params.require(:item).permit(
      :products,
      :condition,
      :description_of_item,
      :price,
      :size,
      :shipping_date,
      :shipping_method,
      :postage,
      :shipping_origin,
      :brand,
      :category,
      images: []
    ).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  

  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_contents.html.haml
.contents
  .contents__image
    = image_tag "index_keyvisual.png", size: "1440x390"
    = image_tag "blog_SNS.png", size: "1440x390" 
  .contents__box
    .contents__category
      %h2 人気のカテゴリー
      .contents__group
        .contents__list
          = link_to "#"  do
            レディース
        .contents__list
          = link_to "#" do
            メンズ
        .contents__list
          = link_to "#" do
            家電・スマホ・カメラ
        .contents__list
          = link_to "#" do
            おもちゃ・ホビー・グッズ
    .contents__main
      .contents__main__top
        %h3 レディース新着アイテム
        .contents__list 
          = link_to "#", target: "_blank" do
            もっと見る
            = fa_icon 'chevron-right'
      .contents--product
        .product__image
          - @items.each do |item|
            .product__img
              .product__imgview
                = link_to item_path(item.id), target: "_blank" do
                  = image_tag item.images[0], class: "product__image", size: "184x188"
                %figure.explanation
                  %figcaption.photo__contents
                    .product__view__name
                      = item.products
                    .pricetag
                      %span.price{"aria-label": "Price"}
                        = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
      .contents__main__top
        %h3 メンズ新着アイテム
        .contents__list
          = link_to "#", target: "_blank" do
            もっと見る
            = fa_icon 'chevron-right'
      .contents--product
        .product__image
          - @items.each do |item|
            .product__img
              .product__imgview
                = link_to item_path(item.id), target: "_blank" do
                  = image_tag item.images[0], class: "product__image", size: "184x188"
                %figure.explanation
                  %figcaption.photo__contents
                    .product__view__name
                      = item.products
                    .pricetag
                      %span.price{"aria-label": "Price"}
                        = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
      .contents__main__top
        %h3 家電・スマホ・カメラ新着アイテム
        .contents__list
          = link_to "#", target: "_blank" do
            もっと見る
            = fa_icon 'chevron-right'
      .contents--product
        .product__image
          - @items.each do |item|
            .product__img
              .product__imgview
                = link_to item_path(item.id), target: "_blank" do
                  = image_tag item.images[0], class: "product__image", size: "184x188"
                %figure.explanation
                  %figcaption.photo__contents
                    .product__view__name
                      = item.products
                    .pricetag
                      %span.price{"aria-label" => "Price"}
                        = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
      .contents__main__top
        %h3 おもちゃ・ホビー・グッズ新着アイテム
        .contents__list
          = link_to "#", target: "_blank" do
            もっと見る
            = fa_icon 'chevron-right'
      .contents--product
        .product__image
          - @items.each do |item|
            .product__img
              .product__imgview
                = link_to item_path(item.id), target: "_blank" do
                  = image_tag item.images[0], class: "product__image", size: "184x188"
                %figure.explanation
                  %figcaption.photo__contents
                    .product__view__name
                      = item.products
                    .pricetag
                      %span.price{"aria-label" => "Price"}
                        = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
    .contents__category__center
      %h2 人気のブランド
      .contents__group
        .contents__list
          = link_to "#" do
            シャネル
        .contents__list
          = link_to "#" do
            ルイヴィトン
        .contents__list
          = link_to "#" do
            シュプリーム
        .contents__list
          = link_to "#" do
            ナイキ
    .contents__main
      .contents__main__top
        %h3 シャネル新着アイテム
        .contents__list
          = link_to "#", target: "_blank" do
            もっと見る
            = fa_icon 'chevron-right'
    .contents--product
      .product__image
        - @items.each do |item|
          .product__img
            .product__imgview
              = link_to item_path(item.id), target: "_blank" do
                = image_tag item.images[0], class: "product__image", size: "184x188"
              %figure.explanation
                %figcaption.photo__contents
                  .product__view__name
                    = item.products
                  .pricetag
                    %span.price{"aria-label" => "Price"}
                      = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
    .contents__main__top
      %h3 ルイヴィトン新着アイテム
      .contents__list
        = link_to "#", target: "_blank" do
          もっと見る
          = fa_icon 'chevron-right'
    .contents--product
      .product__image
        - @items.each do |item|
          .product__img
            .product__imgview
              = link_to item_path(item.id), target: "_blank" do
                = image_tag item.images[0], class: "product__image", size: "184x188"
              %figure.explanation
                %figcaption.photo__contents
                  .product__view__name
                    = item.products
                  .pricetag
                    %span.price{"aria-label" => "Price"}
                      = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
    .contents__main__top
      %h3 シュプリーム新着アイテム
      .contents__list
        = link_to "#", target: "_blank" do
          もっと見る
          = fa_icon 'chevron-right'
    .contents--product
      .product__image
        - @items.each do |item|
          .product__img
            .product__imgview
              = link_to item_path(item.id), target: "_blank" do
                = image_tag item.images[0], class: "product__image", size: "184x188"
              %figure.explanation
                %figcaption.photo__contents
                  .product__view__name
                    = item.products
                  .pricetag
                    %span.price{"aria-label" => "Price"}
                      = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
    .contents__main__top
      %h3 ナイキ新着アイテム
      .contents__list
        = link_to "#", target: "_blank" do
          もっと見る
          = fa_icon 'chevron-right'
    .contents--product
      .product__image
        - @items.each do |item|
          .product__img
            .product__imgview
              = link_to item_path(item.id), target: "_blank" do
                = image_tag item.images[0], class: "product__image", size: "184x188"
              %figure.explanation
                %figcaption.photo__contents
                  .product__view__name
                    = item.products
                  .pricetag
                    %span.price{"aria-label" => "Price"}
                      = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
-# イギリスのところ
%aside.contents__bottom__image
  .contents__bottom__image__detail
    .contents__bottom__image__left
      %p.contents__bottom__left__text
        スマホで簡単フリマアプリ
        %p.contents__bottom__left__texts
          今すぐ無料ダウンロード！
      .contents__bottom__icon
        = image_tag "logo_white.svg", size: "68x68"
        .contents__bottom__app
          = link_to "#", target: "_blank" do
            = image_tag "水.jpg", size: "144x40"
        .contents__bottom__google
          = link_to "#", target: "_blank" do
            = image_tag "水.jpg", size: "144x40"
    .contents__bottom__image__right
      = image_tag "スマホ.jpg", size: "300x260"

app/views/items/_show_items_container.html.haml
%section.item__show-container
  %h1.item__name
    = @item.products
  .item__content
    .buy__photo
      .photo__area
        .photo__area__upper
          .photo__stage
            .photo__item.active
              .photo__item__inner
              -if @item.images.attached?
                - @item.images.each do |image|  
                  =image_tag image,  class: "photo__item__inner"    
        .photo__nav.disabled    
        .photo__dots
          .photo__dot.active
            .photo__dot__inner
            -if @item.images.attached?
              - @item.images.each do |image|  
                =image_tag image, class: "photo__dot__inner"
       
    .item__table
      %table
        %tr
          %th 出品者
          %td
            =link_to @item.user.nickname, mypage_user_path(@item.user.id), class: "table__link"
            .item__user__face 
              .item__user__face__icon
                %i.icon__laugh
                  = fa_icon "smile-o", class: "icon__laugh"
                %span 18
              .item__user__face__icon
                %i.icon__nomal
                  = fa_icon "meh-o", class: "icon__nomal"
                %span 0
              .item__user__face__icon
                %i.icon__sad
                  = fa_icon "frown-o", class: "icon__sad"
                %span 0
        %tr
          %th カテゴリー
          %td
            =link_to @item.category , "#" , class: "table__link"
            =link_to "トップス" , "#", class: "table__link"
            =link_to "ニット/セーター" , "#", class: "table__link"
        %tr
          %th ブランド
          %td 
            =link_to @item.brand, "#",class: "table__link"
        %tr
          %th 商品のサイズ
          %td 
            = @item.size
        %tr
          %th 商品の状態
          %td 
            = @item.condition
        %tr
          %th 配送料の負担
          %td 
            = @item.postage
        %tr
          %th 配送の方法
          %td 
            = @item.shipping_method
        %tr
          %th 配送元地域
          %td 
            = @item.shipping_origin
        %tr
          %th 発送日の目安
          %td 
            = @item.shipping_date
  .item__price
    .item__price__bold 
      ¥
      = @item.price.to_s(:delimited, delimiter: ',')
      %span.item__fee (税込)
      %span.item__total 送料込み
  - if user_signed_in? && current_user.id == @item.user.id
    .item__change__box
      =link_to "商品の編集", edit_item_path(@item.id), class: "btn__default btn__red "
      %p.text__center or
      %form
        %input{type: "hidden"}
      - if user_signed_in? && @item.status == "出品中"
        = link_to "出品を一旦停止する", stopExhibit_item_path(@item), class: "btn__default btn__gray" 
      - else 
        = link_to "出品を再開", resumeExhibit_item_path(@item) , class: "btn__default btn__red"  
      = link_to 'この商品を削除する', item_path(@item.id), class:"btn__default btn__gray", method: :delete
  -else
    =link_to "購入画面に進む", purchase_path(@item.id), class: "item__btn"
    %p.error__message この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
  .item__explanation
  %p.item__explanation__inner 
  = @item.description_of_item
  - if user_signed_in? && current_user.id != @item.user.id 
    .item__btn__content
      .item__btn__left
        =link_to "いいね！", "#", class: "item__btn__like"
        =link_to "不適切な商品の報告", "#", class: "item__btn__like" 
      .item__btn__right
        =link_to "あんぜん・あんしんへの取り組み", "#", class: "item__btn__right"

app/views/items/_show_user_profile.html.haml
.user__profile
  %section.user__items
    %h2.user__items__head
      =link_to "#{@item.user.nickname}さんのその他の商品", "#", class: "user__items__head"
    .user__items__content
      - @items.each do |item|
        %section.items__content
          =link_to "", "#", class: "items__content" 
          %figure.items__photo
            = image_tag item.images[0] ,size: "220x220",alt: "服の画像" , class: "items__photo"
          .items__text
            %h3.items__name 
            = item.products
            .items__num
              .items__price 
                = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
              .items__heart__icon
                %i.icon__like
        
  %section.user__items
    %h2.user__items__head
      =link_to "ノーリーズソフィのニット/セーターその他の商品", "#", class: "user__items__head"
    .user__items__content
      %section.items__content
        =link_to "", "#", class: "items__content"
        %figure.items__photo
          = image_tag "ワンピース.jpg" ,alt: "服の画像" , class: "items__photo"
        .items__text
          %h3.items__name 
          【NOLLEY'S sophi】ワンピース
          .items__num
            .items__price ¥4,730
            .items__heart__icon
              %i.icon__like
      %section.items__content
        =link_to "", "#", class: "items__content"
        %figure.items__photo
          = image_tag "コート.jpg" ,alt: "服の画像" , class: "items__photo"
        .items__text
          %h3.items__name 
          新品ノーリーズ  ノーカラーコート
          .items__num
            .items__price ¥20,800
            .items__heart__icon
              %i.icon__like
      %section.items__content
        =link_to "", "#", class: "items__content"
        %figure.items__photo
          = image_tag "クロップドパンツ.jpg" ,alt: "服の画像" , class: "items__photo"
        .items__text
          %h3.items__name 
          ノーリーズソフィ クロップドパンツ
          .items__num
            .items__price ¥2,200
            .items__heart__icon
              %i.icon__like
      %section.items__content
        =link_to "", "#", class: "items__content"
        %figure.items__photo
          = image_tag "フレアスカート.jpg" ,alt: "服の画像" , class: "items__photo"
        .items__text
          %h3.items__name 
          美品♪秋冬ミディ丈フレアスカート/ダークグリーン
          .items__num
            .items__price ¥8,100
            .items__heart__icon
              %i.icon__like
      %section.items__content
        =link_to "", "#", class: "items__content"
        %figure.items__photo
          = image_tag "切り替えワンピース.jpg" ,alt: "服の画像" , class: "items__photo"
        .items__text
          %h3.items__name 
          ノーリーズ 切替ワンピース 38
          .items__num
            .items__price ¥3,000
            .items__heart__icon
              %i.icon__like
      %section.items__content
        =link_to "", "#", class: "items__content"
        %figure.items__photo
          = image_tag "ファーコート.jpg" ,alt: "服の画像" , class: "items__photo"
        .items__text
          %h3.items__name 
          ♡ ノーリーズ コート ファー ノーカラー ベージュ 36 ♡
          .items__num
            .items__price ¥27,000
            .items__heart__icon
              %i.icon__like            

app/views/items/edit.html.haml
.buy-index__single-wrapper
  .header__single-wrapper
    %h1
      =link_to "", "https://www.mercari.com/jp/"
      =image_tag "fmarket_logo_white.svg", size: "185x49", alt: "mercari"
  %main.sells__single__main
    %section.sells__single__container
      #sells__sell__container
        .sells__data__reactroot
          .sells__sell__container__inner
            %h2.sells__single__head 商品の情報を入力
            %form.sells__sell__form
            = form_with model: @item, url: item_path(@item.id), local:true, class: 'sells__sell__form' do |f|
              .sells__sell__upload__box
                %h3.sells__sell__upload__head 出品画像
                %span.sells__form__require  必須
                %p 最大10枚までアップロードできます
                .sells__sell__dropbox               
                  .sells__sell__upload__items__container
                  = f.label :images, class: 'sells__sell__dropbox' do
                    .sells__sell__upload__drop__box
                      = f.file_field :images, multiple: true, class: 'sell-main__upload-drop-file', style: 'display: none;'
                      .sells__visible__pc ドラッグアンドドロップまたはクリックしてファイルをダウンロード
                      .images__field.clearfix
                        .field
                          = f.label :images 
                          = f.file_field :images, multiple: true, class: "file__input" 
                          -if @item.images.attached? 
                            - @item.images.each do |image|
                              = image_tag image.variant(resize: "150x150"), class: "edit__item__photo"
                              = f.hidden_field :images , name: "item[images][]", value: "#{image.blob.id}", style: "display: none;", class: "item__images__input"
                              = link_to "編集", "", class: "btn__edit"
                              = file_field "edit-image","" , class: "edit__image__file__input file__input", style: "display: none;"
                              = link_to "削除", "", class: "btn__delete"
                      %i.sells__icon__camera  

              .sells__sell__content
                .sells__sell__form__group
                  = f.label :products do
                    商品名
                  %span.sells__form__require 必須
                  .sells__input
                    = f.text_field :products, { class:'sells__input__default', placeholder: '商品名（必須 40文字まで)' }
                    .sells__error__message 入力してください
                .sells__sell__form__group
                  = f.label :description_of_item do
                    商品の説明
                  %span.sells__form__require 必須
                  = f.text_area :description_of_item, { class: 'sells__textarea__default', placeholder: '商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入した購入したジャケットです。ライトグレーで傷はありませんライトグレーで傷はありません。合わせやすいのでおすすめです。' }
                  .sells__style__counter
                    %span 0/1000
                    
                  .sells__error__message 入力してください
              .sells__sell__content.clearfix
                %h3.sells__sell__sub__head 商品の詳細
                .sells__sell__form__box
                  .sells__sell__form__group
                    = f.label :category_id do
                      カテゴリー
                    %span.sells__form__require 必須
                    .sells__select
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :category_id, [['選択してください',1],['レディース',2]], { autofocus: 'true'}, {class:"sells__select__default"}
                        .sells__error__message 選択してください
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :category_id, [['選択してください',1],['トップス',2]], { autofocus: 'true'}, {class:"sells__select__default"}
                        .sells__error__message 選択してください
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :category_id, [['選択してください',1],['ハイヒール/パンプス',2]], { autofocus: 'true'}, {class:"sells__select__default"}
                  .sells__sell__form__group
                    %label サイズ
                    %span.sells__form__require 必須
                    .sells__select
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :size, Item.sizes.keys.to_a, {},autofocus: 'true', class:"sells__select__default"
                        .sells__error__message 選択してください
                  .sells__sell__form__group
                    = f.label :brand_id do
                      ブランド
                    %span.sells__form__require--gray 任意
                    .sells__input
                      = f.text_field :brand_id, { class:'sells__input__default', placeholder: '例）シャネル' }
                  .sells__sell__form__group
                    = f.label :condition do
                      商品の状態
                    %span.sells__form__require 必須
                    .sells__select
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :condition, Item.conditions.keys.to_a, {}, autofocus: 'true', class:"sells__select__default"                       
                        .sells__error__message 選択してください
              .sells__sell__content.clearfix
                .sells__sell__sub
                  %h3.sells__sell_sub__head 配送について
                  .sells__form__question 
                  =link_to "?", "#"
                  .sells__sell__form__box
                    .sells__sell__form__group
                      = f.label :postage do
                        配送料の負担
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :postage, Item.postages.keys.to_a, {}, autofocus: 'true', class:"sells__select__default"
                          .sells__error__message 選択してください
                    .sells__sell__form__group
                      = f.label :shipping_method do
                        配送の方法
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :shipping_method, Item.shipping_methods.keys.to_a, {}, autofocus: 'true', class:"sells__select__default"
                          .sells__error__message 選択してください
                    .sells__sell__form__group
                      = f.label :shipping_origin do
                        発送元の地域
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :shipping_origin, Item.shipping_origins.keys.to_a, {}, autofocus: 'true', class:"sells__select__default"
                          .sells__error__message 選択してください
                    .sells__sell__form__group
                      = f.label :shipping_date do
                        発送までの日数
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :shipping_date, Item.shipping_dates.keys.to_a, {},  autofocus: 'true' , class:"sells__select__default"
                          .sells__error__message 選択してください
              .sells__sell__content.clearfix
                .sells__sell__sub
                  %h3.sells__sell_sub__head 価格(300~9,999,999)
                  =link_to "?", "#", class: "sells__form__question"
                  .sells__sell__form__box
                    %ul.sells__sell__price
                      %li.sells__sell__form__group
                        .clearfix
                          %label.sells__left 販売価格
                          %span.sells__form__require 必須
                          .sells__right 
                            %span
                            = f.text_field :price, { id: 'sells__price', class:'sells__input__default', placeholder: " 例）300" } 
                            .sells__error__message.error__price 300以上9999999以下で入力してください

                      %li.sells__price.clearfix
                        .sells__left--border 販売手数料（10％)
                        %span.sells__right.sells__right1 -
                      %li.sells__price.clearfix.bold
                        .sells__left 販売利益
                        .sells__right.sells__right2#price -
                    .sells__btn

                    = f.submit '変更する', class: 'sells__btn__bottom sell-main__btn-default sell-main__btn-red'
                    =link_to 'キャンセル', items_path(@item.id), class: "sells__btn__bottom__back"

              
                  .sells__sell__btn__box
                    %p
                      禁止されている
                      =link_to "行為", "#" , class: "sells__text__link"
                      および
                      =link_to "出品物", "#", class: "sells__text__link"
                      を必ずご確認ください。
                      =link_to "偽ブランド品", "#", class: "sells__text__link"
                      や
                      =link_to "盗品物" , "#", class: "sells__text__link"
                      などの販売は犯罪であり、法律により処罰される可能性があります。また、出品を持ちまして
                      =link_to "加盟店規約" , "#", class: "sells__text__link"
                      に同意したことになります。




  %footer.content__footer
    %nav
      %ul.footer__nav
        %li
        =link_to "プライバシーポリシー", "#"
        %li
        =link_to "メルカリ利用規約", "#"
        %li
        =link_to "特定商取引に関する表記" , "#"
    =link_to "", "#", class: "footer__logo"
    =image_tag "logo_gray.svg", size: "80x65", alt: "mercari",class: "footer__logo"
    %p
      %small © Mercari, Inc.