config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root'items#index'
  get "/items/show", to: "items#show"
  get  "/buys/index", to: "buys#index"
  get "/sells/index", to: "sells#index"
  get "/cards/index", to: "cards#index"
  
  
  
  
  resources :items  do
    member do
     get :stopExhibit
     get :resumeExhibit
   end
  end
  resources :sells, only: :create
  resources :users, only: [:destroy, :show, :update] do
    collection do
      get 'logout'
    end
    member do
      get 'mypage'
      get 'profile'
      get 'personal'
      get 'sell_item'
    end
    
  end
  resources :signup do
    collection do
      get 'new_member'
      get 'registration'
      get 'sms_confirmation'
      get 'input_address'
      get 'signup_complete'
      end
    end
    resources :cards, only: [:new, :create, :show, :destroy] do
      collection do
        post 'create'
        post 'new'
        post 'show'
        get 'confirmation'
      end
    end
    resources :purchase, only: [:index] do
      member do
        get 'index'
        post 'pay'
        get 'done'
      end
    end
  end

app/controllers/sells_controller.rb
class SellsController < ApplicationController

  def index
    @item = Item.new
  end
  
  def create
    
    @item = Item.new(item_params) 
    if @item.save
      redirect_to root_path, notice: '商品を出品しました'
    else
      render :index
    end
    
  end

   
    private
  def item_params
    params.require(:item).permit(
      :products,
      :condition,
      :description_of_item,
      :price,
      :size,
      :shipping_date,
      :shipping_method,
      :postage,
      :shipping_origin,
      :brand,
      :category,
      images: []
    ).merge(user_id: current_user.id)
  end
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/sells/_error-message.html.haml
- if @item.errors.any?
  - unless @item.valid?
    - if errors = @item.errors.full_messages_for(column.to_sym)
      - errors.each do |error|
        .sells__error__message
          = error

app/views/sells/index.html.haml
.buy-index__single-wrapper
  .header__single-wrapper
    %h1
      =link_to root_path do
        =image_tag "fmarket_logo_white.svg", size: "185x49", alt: "mercari"
  %main.sells__single__main
    %section.sells__single__container
      #sells__sell__container
        .sells__data__reactroot
          .sells__sell__container__inner
            %h2.sells__single__head 商品の情報を入力
            %form.sells__sell__form
            = form_with model: @item, url: sells_path, local:true, method: :post, class: 'sells__sell__form' do |f|
              .sells__sell__upload__box
                %h3.sells__sell__upload__head 出品画像
                %span.sells__form__require  必須
                %p 最大10枚までアップロードできます
                .sells__sell__dropbox               
                  .sells__sell__upload__items__container
                  = f.label :images, class: 'sells__sell__dropbox' do
                    .sells__sell__upload__drop__box
                      = f.file_field :images, multiple: true, class: 'sell-main__upload-drop-file', style: 'display: none;'
                      .sells__visible__pc ドラッグアンドドロップまたはクリックしてファイルをダウンロード
                      %i.sells__icon__camera 
                  .sells__images__error
                    = render partial: "error-message", locals:{item: @item, column: :images}


              .sells__sell__content
                .sells__sell__form__group
                  = f.label :products do
                    商品名
                  %span.sells__form__require 必須
                  .sells__input
                    = f.text_field :products, { class:'sells__input__default', placeholder: '商品名（必須 40文字まで)' }
                    = render partial: "error-message", locals:{item: @item, column: :products}
                .sells__sell__form__group
                  = f.label :description_of_item do
                    商品の説明
                  %span.sells__form__require 必須
                  = f.text_area :description_of_item, { class: 'sells__textarea__default', placeholder: '商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入した購入したジャケットです。ライトグレーで傷はありませんライトグレーで傷はありません。合わせやすいのでおすすめです。' }
                  .sells__style__counter
                    %span 0/1000
                  = render partial: "error-message", locals:{item: @item, column: :description_of_item}
              .sells__sell__content.clearfix
                %h3.sells__sell__sub__head 商品の詳細
                .sells__sell__form__box
                  .sells__sell__form__group
                    = f.label :category do
                      カテゴリー
                    %span.sells__form__require 必須
                    .sells__select
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :category, Item.categories.keys.to_a, { autofocus: 'true'}, {class:"sells__select__default"}
                        = render partial: "error-message", locals:{item: @item, column: :category}
                      -# .sells__select__wrap
                      -#   %i.sells__icon__arrow
                      -#   = f.select :category, [['選択してください',1],['トップス',2]], { autofocus: 'true'}, {class:"sells__select__default"}
                      -#   .sells__error__message 選択してください
                      -# .sells__select__wrap
                      -#   %i.sells__icon__arrow
                      -#   = f.select :category, [['選択してください',1],['ハイヒール/パンプス',2]], { autofocus: 'true'}, {class:"sells__select__default"}
                  .sells__sell__form__group
                    %label サイズ
                    %span.sells__form__require 必須
                    .sells__select
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :size, Item.sizes.keys.to_a, {},autofocus: 'true', class:"sells__select__default"
                        = render partial: "error-message", locals:{item: @item, column: :size}
                  .sells__sell__form__group
                    = f.label :brand do
                      ブランド
                    %span.sells__form__require--gray 任意
                    .sells__input
                      = f.text_field :brand, { class:'sells__input__default', placeholder: '例）シャネル' }
                  .sells__sell__form__group
                    = f.label :condition do
                      商品の状態
                    %span.sells__form__require 必須
                    .sells__select
                      .sells__select__wrap
                        %i.sells__icon__arrow
                        = f.select :condition, Item.conditions.keys.to_a, {}, autofocus: 'true', class:"sells__select__default"                       
                        = render partial: "error-message", locals:{item: @item, column: :condition}
              .sells__sell__content.clearfix
                .sells__sell__sub
                  %h3.sells__sell_sub__head 配送について
                  .sells__form__question 
                  -# =link_to "?", "#", class: "sells__form__question"
                  .sells__sell__form__box
                    .sells__sell__form__group
                      = f.label :postage do
                        配送料の負担
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :postage, Item.postages.keys.to_a, {}, autofocus: 'true', class:"sells__select__default"
                          = render partial: "error-message", locals:{item: @item, column: :postage}
                    .sells__sell__form__group
                      = f.label :shipping_method do
                        配送の方法
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :shipping_method, Item.shipping_methods.keys.to_a, {}, autofocus: 'true', class:"sells__select__default" 
                          = render partial: "error-message", locals:{item: @item, column: :shipping_method}
                    .sells__sell__form__group
                      = f.label :shipping_origin do
                        発送元の地域
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :shipping_origin, Item.shipping_origins.keys.to_a, {}, autofocus: 'true', class:"sells__select__default" 
                          = render partial: "error-message", locals:{item: @item, column: :shipping_origin}
                    .sells__sell__form__group
                      = f.label :shipping_date do
                        発送までの日数
                      %span.sells__form__require 必須
                      .sells__select
                        .sells__select__wrap
                          %i.sells__icon__arrow
                          = f.select :shipping_date, Item.shipping_dates.keys.to_a, {},  autofocus: 'true' , class:"sells__select__default"
                          = render partial: "error-message", locals:{item: @item, column: :shipping_date}
              .sells__sell__content.clearfix
                .sells__sell__sub
                  %h3.sells__sell_sub__head 価格(300~9,999,999)
                  =link_to "?", "#", class: "sells__form__question"
                  .sells__sell__form__box
                    %ul.sells__sell__price
                      %li.sells__sell__form__group
                        .clearfix
                          %label.sells__left 販売価格
                          %span.sells__form__require 必須
                          .sells__right 
                            %span
                            = f.text_field :price, { id: 'sells__price', class:'sells__input__default', placeholder: " 例）300" } 
                            .error__price 
                            = render partial: "error-message", locals:{item: @item, column: :price}

                      %li.sells__price.clearfix
                        .sells__left--border 販売手数料（10％)
                        %span.sells__right.sells__right1 -
                      %li.sells__price.clearfix.bold
                        .sells__left 販売利益
                        .sells__right.sells__right2#price -
                    .sells__btn
                    = f.submit '出品する', class: 'sells__btn__bottom sell-main__btn-default sell-main__btn-red'
                    =link_to "もどる", sell_item_user_path(current_user.id), class: "sells__btn__bottom__back"
                  .sells__sell__btn__box
                    %p
                      禁止されている
                      =link_to "行為", "#" , class: "sells__text__link"
                      および
                      =link_to "出品物", "#", class: "sells__text__link"
                      を必ずご確認ください。
                      =link_to "偽ブランド品", "#", class: "sells__text__link"
                      や
                      =link_to "盗品物" , "#", class: "sells__text__link"
                      などの販売は犯罪であり、法律により処罰される可能性があります。また、出品を持ちまして
                      =link_to "加盟店規約" , "#", class: "sells__text__link"
                      に同意したことになります。
  %footer.content__footer
    %nav
      %ul.footer__nav
        %li
        =link_to "プライバシーポリシー", "#"
        %li
        =link_to "メルカリ利用規約", "#"
        %li
        =link_to "特定商取引に関する表記" , "#"
    =link_to "", "#", class: "footer__logo"
    =image_tag "logo_gray.svg", size: "80x65", alt: "mercari",class: "footer__logo"
    %p
      %small © Mercari, Inc.

app/views/sells/show.html.haml
%p
  %strong images:
  - @item.images.each do |image|
    = image_tag image.variant(resize: "150x150")